# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-7O8c46a2AKcLea2ocRIOwp-ITcVZsa

## CNN
Convulutional Neural Network is used for processing image data and visualizing data.It learns textures,shapes,edges,object from the image. Mainly used for object detection ,face recognition , image classification.

Workflow of CNN :- Image --> Convolutional layer (here padding also takes place) --> Pooling --> Flatten --> Neural Network --> Output.

Important Terms in CNN :-

## kernel/Filter
It is nothing but the filter which is used to extract the features from input data basically it stores the data in 3X3 matrix this is a default value.Moves input data points in matrix using stride values.

## Stride
It is the value for kernel matrix to scan a pixel at a time.If stride value is 2 then kernel matrix will scan 2 pixels at a time. Decides how the kernel will scan the pixels or how the kernel will cover the data points in a matrix.

## Padding
Used to avoid the data missing problem like border problem.Covers the data points which lies in border it is used to consider these border data points or pixels.

## Pooling
It is used to reduce the extra features from the extracted ones after padding takes place.Basically used for dimensionality reduction and making the data compact.

##  Flatten
It is layer which organize the important features which are collected from pooling layer in a well structured format/column. No.of flatten layer and convolutional layer is equal. Means every convolutional layer requires it separate flatten layer.
"""

import tensorflow as tf
from tensorflow.keras import datasets,layers,models
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,classification_report

(X_train, y_train), (X_test, y_test) = datasets.fashion_mnist.load_data()

print("Training images :", X_train.shape)
print("Training labels :", y_train.shape)
print("Test images :", X_test.shape)
print("Test labels :", y_test.shape)

print("First 10 labels:",y_train[:10])

class_names=["T-shirt/top","Trouser","Pullover","Dress","Coat","Sandal","Shirt","Sneaker","Bag","Ankle boot"]
for i,name in enumerate(class_names):
  print(i,"->",name)

plt.figure(figsize=(1,2))
plt.imshow(X_train[5],cmap="gray")
plt.title(class_names[y_train[5]])
plt.show()

plt.figure(figsize=(10,5))
for i in range(10):
  plt.subplot(2,5,i+1)
  plt.imshow(X_train[i],cmap="gray")
  plt.title(class_names[y_train[i]])
  plt.axis("off")
plt.tight_layout()
plt.show()

print("Minimum pixel value :",X_train.min())
print("Maximum pixel value :",X_train.max())

X_train=X_train.astype("float32")/255.0
X_test=X_test.astype("float32")/255.0
print("Minimum after normalization :",X_train.min())
print("Maximum after normalization :",X_train.max())

X_train=np.expand_dims(X_train,axis=-1)
X_test=np.expand_dims(X_test,axis=-1)
print("X_train shape:",X_train.shape)
print("X_test shape:",X_test.shape)

cnn=models.Sequential([layers.Input(shape=(28,28,1)),
                       layers.Conv2D(32,(3,3),activation="relu"),
                       layers.MaxPooling2D((2,2)),
                       layers.Conv2D(64,(3,3),activation="relu"),
                       layers.MaxPooling2D((2,2)),
                       layers.Flatten(),
                       layers.Dense(128,activation="relu"),
                       layers.Dropout(0.5),
                       layers.Dense(10,activation="softmax")])

cnn.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

history=cnn.fit(X_train,y_train,epochs=10,validation_split=0.1,batch_size=64)

plt.figure(figsize=(8,5))
plt.plot(history.history["accuracy"],label="Training Accuyracy")

plt.plot(history.history["accuracy"],label="accuracy")
plt.plot(history.history["val_accuracy"],label="val_accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(loc="lower right")
plt.show













